languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Transylvania Sprint"
copyright = "Â© 2024 transylvania sprint organizers"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Nix/OS hackathon in Transylvania, Romania"

[params.author]
  name = "Transylvania Sprint"
  image = "img/logo.svg"
  headline = "One week of Nix/OS hacking in Romania"
  links = [
    { email = "mailto:transylvaniasprint@gmail.com" },
  #   { link = "https://link-to-some-website.com/" },
    { github = "https://github.com/transylvania-sprint/transylvaniasprint.org" },
    { mastodon = "https://mastodon.instance/@username" },
  ]
